name: CI
on:
  - push
  - pull_request

defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev --deploy
      - name: Check dependencies for security vulnerabilities and against PEP 508
        run: |
          pipenv check
      - name: Check black formatting
        run: |
          pipenv run black --check .
      - name: Check import sort
        run: |
          pipenv run isort --check .
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev --deploy
      - name: Run test suite
        run: |
          pipenv run coverage run --source unilogin manage.py test
      - name: Report coverage to Coveralls
        run: |
          pipenv run coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}